/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Telas.Tela03_B_HomeGerencia;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.Funcionarios;
import model.FuncionariosDao;

/**
 *
 * @author Denise Trevizo (usp)
 */
public class Tela04_B6_TabbedFuncionarios extends javax.swing.JFrame {

    /**
     * Creates new form TabbedClientesGerencia
     */
    public Tela04_B6_TabbedFuncionarios() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        voltarFuncionarios = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaFunc = new javax.swing.JTable();
        pesquisaFunc = new javax.swing.JTextField();
        pesquisarFunc = new javax.swing.JButton();
        voltarFuncionarios1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nomeCadFunc = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        atualizarCadFunc = new javax.swing.JButton();
        voltarCadFunc = new javax.swing.JButton();
        excluirCadFunc = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        paiCadFunc = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        maeCadFunc = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        civilCadFunc = new javax.swing.JComboBox<>();
        rgCadFunc = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        eleitorCadFunc = new javax.swing.JFormattedTextField();
        cpfCadFunc = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        nascCadFunc = new javax.swing.JFormattedTextField();
        telCadFunc = new javax.swing.JFormattedTextField();
        celCadFunc = new javax.swing.JFormattedTextField();
        jLabel34 = new javax.swing.JLabel();
        avancar2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        voltarCadFunc1 = new javax.swing.JButton();
        excluirCadFunc1 = new javax.swing.JButton();
        atualizarCadFunc1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        endCadFunc = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        bairroCadFunc = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        compCadFunc = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        end_numCadFunc = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        cepCadFunc = new javax.swing.JFormattedTextField();
        jLabel23 = new javax.swing.JLabel();
        emailCadFunc = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        natCadFunc = new javax.swing.JTextField();
        nat_ufCadFunc = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        nacCadFunc = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cidadeCadFunc = new javax.swing.JTextField();
        cidade_ufCadFunc = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        camCadFunc = new javax.swing.JFormattedTextField();
        jLabel25 = new javax.swing.JLabel();
        avancar3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        voltarCadFunc2 = new javax.swing.JButton();
        excluirCadFunc2 = new javax.swing.JButton();
        inserirCadFunc2 = new javax.swing.JButton();
        atualizarCadFunc2 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        ctpsCadFunc = new javax.swing.JFormattedTextField();
        pisCadFunc = new javax.swing.JFormattedTextField();
        jLabel28 = new javax.swing.JLabel();
        cargoCadFunc = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jornadaCadFunc = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        admissaoCadFunc = new javax.swing.JFormattedTextField();
        remunerCadFunc = new javax.swing.JTextField();
        uf_ctpsCadFunc = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(242, 242, 242));
        jTabbedPane1.setForeground(new java.awt.Color(67, 1, 101));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTabbedPane1.setOpaque(true);
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 208, 119));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(67, 1, 101));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Consultar Funcionários");
        jLabel2.setOpaque(true);

        voltarFuncionarios.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        voltarFuncionarios.setForeground(new java.awt.Color(204, 0, 0));
        voltarFuncionarios.setText("<<");
        voltarFuncionarios.setBorderPainted(false);
        voltarFuncionarios.setContentAreaFilled(false);
        voltarFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarFuncionariosActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tabelaFunc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tabelaFunc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "CPF", "RG", "Data Nasc.", "Pai", "Mãe", "Est. Civil", "Tit. Eleitor", "Nacional.", "Natural.", "UF Natal", "CAM", "Telefone", "Celular", "Endereço", "Cidade", "Bairro", "CEP", "UF Cidade", "E-mail", "PIS/PASEP", "CTPS", "UF CTPS", "Cargo", "Data Admissão", "Salário", "Jornada"
            }
        ));
        tabelaFunc.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabelaFunc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaFuncMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaFunc);

        pesquisaFunc.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        pesquisarFunc.setBackground(new java.awt.Color(30, 0, 45));
        pesquisarFunc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pesquisarFunc.setForeground(new java.awt.Color(255, 255, 255));
        pesquisarFunc.setText("Pesquisar");
        pesquisarFunc.setBorderPainted(false);
        pesquisarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarFuncActionPerformed(evt);
            }
        });

        voltarFuncionarios1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        voltarFuncionarios1.setForeground(new java.awt.Color(36, 99, 36));
        voltarFuncionarios1.setText(">>");
        voltarFuncionarios1.setBorderPainted(false);
        voltarFuncionarios1.setContentAreaFilled(false);
        voltarFuncionarios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarFuncionarios1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(voltarFuncionarios)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(pesquisaFunc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pesquisarFunc))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(voltarFuncionarios1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 270, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(voltarFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(voltarFuncionarios1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pesquisarFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pesquisaFunc, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Consulta", jPanel3);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 208, 119));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(67, 1, 101));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastrar Funcionários I");
        jLabel1.setOpaque(true);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Estado Civil");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Nome");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Data Nasc.");

        atualizarCadFunc.setBackground(new java.awt.Color(30, 0, 45));
        atualizarCadFunc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        atualizarCadFunc.setForeground(new java.awt.Color(255, 255, 255));
        atualizarCadFunc.setText("Atualizar");
        atualizarCadFunc.setBorderPainted(false);
        atualizarCadFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarCadFuncActionPerformed(evt);
            }
        });

        voltarCadFunc.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        voltarCadFunc.setForeground(new java.awt.Color(204, 0, 0));
        voltarCadFunc.setText("<<");
        voltarCadFunc.setBorderPainted(false);
        voltarCadFunc.setContentAreaFilled(false);
        voltarCadFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarCadFuncActionPerformed(evt);
            }
        });

        excluirCadFunc.setBackground(new java.awt.Color(30, 0, 45));
        excluirCadFunc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        excluirCadFunc.setForeground(new java.awt.Color(255, 255, 255));
        excluirCadFunc.setText("Excluir");
        excluirCadFunc.setBorderPainted(false);
        excluirCadFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirCadFuncActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Filiação");

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Pai");

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Mãe");

        civilCadFunc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        civilCadFunc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solteiro(a)", "Casado(a)", "Divorciado(a)", "Separado(a)", "Viúvo(a)", "Outro" }));
        civilCadFunc.setOpaque(false);
        civilCadFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                civilCadFuncActionPerformed(evt);
            }
        });

        try {
            rgCadFunc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("RG");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Título de Eleitor");

        try {
            eleitorCadFunc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#### #### #### ##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            cpfCadFunc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpfCadFunc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cpfCadFuncFocusLost(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("CPF");

        try {
            nascCadFunc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            telCadFunc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            celCadFunc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel34.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(51, 51, 51));
        jLabel34.setText("Telefone / Celular");

        avancar2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        avancar2.setForeground(new java.awt.Color(36, 99, 36));
        avancar2.setText(">>");
        avancar2.setBorderPainted(false);
        avancar2.setContentAreaFilled(false);
        avancar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avancar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(voltarCadFunc)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(242, 257, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel16))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(maeCadFunc)
                                            .addComponent(paiCadFunc)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(telCadFunc)
                            .addComponent(celCadFunc)
                            .addComponent(jLabel10)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nomeCadFunc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cpfCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(civilCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(0, 34, Short.MAX_VALUE))
                                    .addComponent(nascCadFunc)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(excluirCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(rgCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(eleitorCadFunc)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(8, 8, 8))))
                            .addComponent(atualizarCadFunc, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(16, 16, 16)
                .addComponent(avancar2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(voltarCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(avancar2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomeCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cpfCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel34))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(paiCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(telCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maeCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(celCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(eleitorCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rgCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nascCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(civilCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel4))
                                    .addGap(38, 38, 38))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(excluirCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(atualizarCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))))
        );

        jTabbedPane1.addTab("Cadastro I", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setBackground(new java.awt.Color(255, 208, 119));
        jLabel6.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(67, 1, 101));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Cadastrar Funcionários II");
        jLabel6.setOpaque(true);

        voltarCadFunc1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        voltarCadFunc1.setForeground(new java.awt.Color(204, 0, 0));
        voltarCadFunc1.setText("<<");
        voltarCadFunc1.setBorderPainted(false);
        voltarCadFunc1.setContentAreaFilled(false);
        voltarCadFunc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarCadFunc1ActionPerformed(evt);
            }
        });

        excluirCadFunc1.setBackground(new java.awt.Color(30, 0, 45));
        excluirCadFunc1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        excluirCadFunc1.setForeground(new java.awt.Color(255, 255, 255));
        excluirCadFunc1.setText("Excluir");
        excluirCadFunc1.setBorderPainted(false);
        excluirCadFunc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirCadFunc1ActionPerformed(evt);
            }
        });

        atualizarCadFunc1.setBackground(new java.awt.Color(30, 0, 45));
        atualizarCadFunc1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        atualizarCadFunc1.setForeground(new java.awt.Color(255, 255, 255));
        atualizarCadFunc1.setText("Atualizar");
        atualizarCadFunc1.setBorderPainted(false);
        atualizarCadFunc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarCadFunc1ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Endereço");

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("Bairro");

        jLabel19.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("Comp");

        jLabel20.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setText("Nº");

        jLabel22.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setText("CEP");

        try {
            cepCadFunc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel23.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setText("E-mail");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Naturalidade");

        jLabel21.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setText("UF");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Nacionalidade");

        jLabel24.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setText("UF");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Cidade");

        try {
            camCadFunc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.######.#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel25.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 51, 51));
        jLabel25.setText("CAM");

        avancar3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        avancar3.setForeground(new java.awt.Color(36, 99, 36));
        avancar3.setText(">>");
        avancar3.setBorderPainted(false);
        avancar3.setContentAreaFilled(false);
        avancar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avancar3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(voltarCadFunc1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(excluirCadFunc1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(bairroCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(compCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(emailCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(atualizarCadFunc1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12)
                            .addComponent(endCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel20)
                            .addComponent(end_numCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cepCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(camCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cidadeCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(cidade_ufCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nacCadFunc)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(0, 20, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(natCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(nat_ufCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(avancar3)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(voltarCadFunc1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(avancar3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel21)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(natCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nat_ufCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nacCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cidadeCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cidade_ufCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(camCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel20)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(endCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(end_numCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cepCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bairroCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(compCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(atualizarCadFunc1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(excluirCadFunc1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(29, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Cadastro II", jPanel2);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel26.setBackground(new java.awt.Color(255, 208, 119));
        jLabel26.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(67, 1, 101));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Cadastrar Funcionários III");
        jLabel26.setOpaque(true);

        voltarCadFunc2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        voltarCadFunc2.setForeground(new java.awt.Color(204, 0, 0));
        voltarCadFunc2.setText("<<");
        voltarCadFunc2.setBorderPainted(false);
        voltarCadFunc2.setContentAreaFilled(false);
        voltarCadFunc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarCadFunc2ActionPerformed(evt);
            }
        });

        excluirCadFunc2.setBackground(new java.awt.Color(30, 0, 45));
        excluirCadFunc2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        excluirCadFunc2.setForeground(new java.awt.Color(255, 255, 255));
        excluirCadFunc2.setText("Excluir");
        excluirCadFunc2.setBorderPainted(false);
        excluirCadFunc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirCadFunc2ActionPerformed(evt);
            }
        });

        inserirCadFunc2.setBackground(new java.awt.Color(30, 0, 45));
        inserirCadFunc2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        inserirCadFunc2.setForeground(new java.awt.Color(255, 255, 255));
        inserirCadFunc2.setText("Inserir");
        inserirCadFunc2.setBorderPainted(false);
        inserirCadFunc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirCadFunc2ActionPerformed(evt);
            }
        });

        atualizarCadFunc2.setBackground(new java.awt.Color(30, 0, 45));
        atualizarCadFunc2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        atualizarCadFunc2.setForeground(new java.awt.Color(255, 255, 255));
        atualizarCadFunc2.setText("Atualizar");
        atualizarCadFunc2.setBorderPainted(false);
        atualizarCadFunc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarCadFunc2ActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 51, 51));
        jLabel27.setText("CTPS");

        try {
            ctpsCadFunc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####### ###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            pisCadFunc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.#####.##-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel28.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 51, 51));
        jLabel28.setText("PIS/PASEP");

        jLabel29.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 51, 51));
        jLabel29.setText("Cargo");

        jLabel30.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 51, 51));
        jLabel30.setText("Remuneração");

        jLabel31.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(51, 51, 51));
        jLabel31.setText("Jornada de trabalho");

        jLabel32.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(51, 51, 51));
        jLabel32.setText("Data de Admissão");

        try {
            admissaoCadFunc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel33.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(51, 51, 51));
        jLabel33.setText("UF");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(voltarCadFunc2)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(admissaoCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel30)
                                        .addGap(0, 36, Short.MAX_VALUE))
                                    .addComponent(remunerCadFunc))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jornadaCadFunc)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(excluirCadFunc2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(atualizarCadFunc2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inserirCadFunc2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cargoCadFunc, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(81, 81, 81))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(pisCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(ctpsCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(uf_ctpsCadFunc)
                                .addGap(81, 81, 81))))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pisCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ctpsCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(uf_ctpsCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cargoCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jornadaCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(jLabel30))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(admissaoCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(remunerCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(voltarCadFunc2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(excluirCadFunc2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inserirCadFunc2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(atualizarCadFunc2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))))
        );

        jTabbedPane1.addTab("Cadastro III", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   public void limparFuncionario(){
            nomeCadFunc.setText("");
            cpfCadFunc.setText("");
            nascCadFunc.setText("");
            paiCadFunc.setText("");
            telCadFunc.setText("");
            maeCadFunc.setText("");
            celCadFunc.setText("");
            //civilCadFunc.setText(String.valueOf(f.getestado_civil()));
            rgCadFunc.setText("");
            eleitorCadFunc.setText("");
            nacCadFunc.setText("");
            natCadFunc.setText("");
            nat_ufCadFunc.setText("");
            camCadFunc.setText("");
            cidadeCadFunc.setText("");
            cidade_ufCadFunc.setText("");
            endCadFunc.setText("");
            cepCadFunc.setText("");
            bairroCadFunc.setText("");
            emailCadFunc.setText("");
            pisCadFunc.setText("");
            ctpsCadFunc.setText("");
            uf_ctpsCadFunc.setText("");
            cargoCadFunc.setText("");
            admissaoCadFunc.setText("");
            remunerCadFunc.setText("");
            jornadaCadFunc.setText("");
}
   
    private void voltarFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarFuncionariosActionPerformed
        Tela03_B_HomeGerencia telaHomeGerencia = new Tela03_B_HomeGerencia();
        telaHomeGerencia.setVisible(true);
        dispose();
    }//GEN-LAST:event_voltarFuncionariosActionPerformed

    private void atualizarCadFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarCadFuncActionPerformed
        Funcionarios Funcionarios = new Funcionarios();
        FuncionariosDao cdao = new FuncionariosDao();
        
        // Fill Form
        Funcionarios.setnome(nomeCadFunc.getText());
        Funcionarios.setcpf(cpfCadFunc.getText());
        Funcionarios.setrg(rgCadFunc.getText());
        Funcionarios.setdata_nascimento(nascCadFunc.getText());
        Funcionarios.setnome_pai(paiCadFunc.getText());
        Funcionarios.setnome_mae(maeCadFunc.getText());
        Funcionarios.setestado_civil(String.valueOf(civilCadFunc.getSelectedItem()));   
        Funcionarios.settitulo_eleitor(eleitorCadFunc.getText());
        Funcionarios.setnacionalidade(nacCadFunc.getText());
        Funcionarios.setnaturalidade(natCadFunc.getText());
        Funcionarios.setuf_n(nat_ufCadFunc.getText());
        Funcionarios.setcam(camCadFunc.getText());  
        Funcionarios.settelefone(telCadFunc.getText());
        Funcionarios.setcelular(celCadFunc.getText());
        Funcionarios.setendereco(endCadFunc.getText() + "," + end_numCadFunc.getText());
        Funcionarios.setcidade(cidadeCadFunc.getText());
        Funcionarios.setbairro(bairroCadFunc.getText());
        Funcionarios.setcep(cepCadFunc.getText());
        Funcionarios.setuf(cidade_ufCadFunc.getText());
        Funcionarios.setemail(emailCadFunc.getText());
        Funcionarios.setpis_pasep(pisCadFunc.getText());
        Funcionarios.setctps(ctpsCadFunc.getText());
        Funcionarios.setuf_c(uf_ctpsCadFunc.getText());
        Funcionarios.setcargo(cargoCadFunc.getText());
        Funcionarios.setdata_admissao(admissaoCadFunc.getText());
        Funcionarios.setremuneracao(Float.parseFloat(remunerCadFunc.getText()));         
        Funcionarios.sethorario_trabalho(Integer.parseInt(jornadaCadFunc.getText()));   
        Funcionarios.setcpf(cpfCadFunc.getText());
        cdao.update(Funcionarios);
        
        // Clear Form
        limparFuncionario();
    }//GEN-LAST:event_atualizarCadFuncActionPerformed

    private void voltarCadFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarCadFuncActionPerformed
        //Volta para a tela de consulta
        jTabbedPane1.setSelectedIndex(0);
        
        limparFuncionario();
    }//GEN-LAST:event_voltarCadFuncActionPerformed

    private void excluirCadFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirCadFuncActionPerformed
        Funcionarios Funcionarios = new Funcionarios();
        FuncionariosDao cdao = new FuncionariosDao();
        // Fill Form

        Funcionarios.setcpf(cpfCadFunc.getText()); 
        cdao.delete(Funcionarios);
        
        // Clear Form
        limparFuncionario();
    }//GEN-LAST:event_excluirCadFuncActionPerformed

    private void civilCadFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_civilCadFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_civilCadFuncActionPerformed

    private void voltarCadFunc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarCadFunc1ActionPerformed
        //Volta para a tela de cadastro I
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_voltarCadFunc1ActionPerformed

    private void voltarCadFunc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarCadFunc2ActionPerformed
        //Volta para a tela de cadastro II
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_voltarCadFunc2ActionPerformed

    private void excluirCadFunc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirCadFunc2ActionPerformed
        Funcionarios Funcionarios = new Funcionarios();
        FuncionariosDao cdao = new FuncionariosDao();
        // Fill Form

        Funcionarios.setcpf(cpfCadFunc.getText()); 
        cdao.delete(Funcionarios);
        
        // Clear Form
        limparFuncionario();
    }//GEN-LAST:event_excluirCadFunc2ActionPerformed

    private void inserirCadFunc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirCadFunc2ActionPerformed
        Funcionarios Funcionarios = new Funcionarios();
        FuncionariosDao cdao = new FuncionariosDao();
        
        // Fill Form
        Funcionarios.setnome(nomeCadFunc.getText());
        Funcionarios.setcpf(cpfCadFunc.getText());
        Funcionarios.setrg(rgCadFunc.getText());
        Funcionarios.setdata_nascimento(nascCadFunc.getText());
        Funcionarios.setnome_pai(paiCadFunc.getText());
        Funcionarios.setnome_mae(maeCadFunc.getText());
        Funcionarios.setestado_civil(String.valueOf(civilCadFunc.getSelectedItem()));   
        Funcionarios.settitulo_eleitor(eleitorCadFunc.getText());
        Funcionarios.setnacionalidade(nacCadFunc.getText());
        Funcionarios.setnaturalidade(natCadFunc.getText());
        Funcionarios.setuf_n(nat_ufCadFunc.getText());
        Funcionarios.setcam(camCadFunc.getText());  
        Funcionarios.settelefone(telCadFunc.getText());
        Funcionarios.setcelular(celCadFunc.getText());
        Funcionarios.setendereco(endCadFunc.getText() + "," + end_numCadFunc.getText());
        Funcionarios.setcidade(cidadeCadFunc.getText());
        Funcionarios.setbairro(bairroCadFunc.getText());
        Funcionarios.setcep(cepCadFunc.getText());
        Funcionarios.setuf(cidade_ufCadFunc.getText());
        Funcionarios.setemail(emailCadFunc.getText());
        Funcionarios.setpis_pasep(pisCadFunc.getText());
        Funcionarios.setctps(ctpsCadFunc.getText());
        Funcionarios.setuf_c(uf_ctpsCadFunc.getText());
        Funcionarios.setcargo(cargoCadFunc.getText());
        Funcionarios.setdata_admissao(admissaoCadFunc.getText());
        Funcionarios.setremuneracao(Float.parseFloat(remunerCadFunc.getText()));         
        Funcionarios.sethorario_trabalho(Integer.parseInt(jornadaCadFunc.getText()));    
        cdao.create(Funcionarios);
        
        // Clear Form
        limparFuncionario();
    }//GEN-LAST:event_inserirCadFunc2ActionPerformed

    private void atualizarCadFunc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarCadFunc2ActionPerformed
        Funcionarios Funcionarios = new Funcionarios();
        FuncionariosDao cdao = new FuncionariosDao();
        
        // Fill Form
        Funcionarios.setnome(nomeCadFunc.getText());
        Funcionarios.setcpf(cpfCadFunc.getText());
        Funcionarios.setrg(rgCadFunc.getText());
        Funcionarios.setdata_nascimento(nascCadFunc.getText());
        Funcionarios.setnome_pai(paiCadFunc.getText());
        Funcionarios.setnome_mae(maeCadFunc.getText());
        Funcionarios.setestado_civil(String.valueOf(civilCadFunc.getSelectedItem()));   
        Funcionarios.settitulo_eleitor(eleitorCadFunc.getText());
        Funcionarios.setnacionalidade(nacCadFunc.getText());
        Funcionarios.setnaturalidade(natCadFunc.getText());
        Funcionarios.setuf_n(nat_ufCadFunc.getText());
        Funcionarios.setcam(camCadFunc.getText());  
        Funcionarios.settelefone(telCadFunc.getText());
        Funcionarios.setcelular(celCadFunc.getText());
        Funcionarios.setendereco(endCadFunc.getText() + "," + end_numCadFunc.getText());
        Funcionarios.setcidade(cidadeCadFunc.getText());
        Funcionarios.setbairro(bairroCadFunc.getText());
        Funcionarios.setcep(cepCadFunc.getText());
        Funcionarios.setuf(cidade_ufCadFunc.getText());
        Funcionarios.setemail(emailCadFunc.getText());
        Funcionarios.setpis_pasep(pisCadFunc.getText());
        Funcionarios.setctps(ctpsCadFunc.getText());
        Funcionarios.setuf_c(uf_ctpsCadFunc.getText());
        Funcionarios.setcargo(cargoCadFunc.getText());
        Funcionarios.setdata_admissao(admissaoCadFunc.getText());
        Funcionarios.setremuneracao(Float.parseFloat(remunerCadFunc.getText()));         
        Funcionarios.sethorario_trabalho(Integer.parseInt(jornadaCadFunc.getText()));   
        Funcionarios.setcpf(cpfCadFunc.getText());
        cdao.update(Funcionarios);
        
        // Clear Form
        limparFuncionario();
    }//GEN-LAST:event_atualizarCadFunc2ActionPerformed

    private void pesquisarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarFuncActionPerformed
        DefaultTableModel tabelaFuncionarios = (DefaultTableModel) tabelaFunc.getModel(); 
        tabelaFuncionarios.setNumRows(0);
        FuncionariosDao dao = new FuncionariosDao(); 
        //Produtos p = Produtos.getProdutoPorID(Integer.parseInt(codCadProd.getText()));
        for (Funcionarios c : dao.getContatos(pesquisaFunc.getText().toString())) {
            tabelaFuncionarios.addRow(new Object[]{c.getcod_func(), c.getnome(), 
                c.getcpf(), c.getrg(), c.getdata_nacimento(), c.getnome_pai(),
                c.getnome_mae(), c.getestado_civil(), c.gettitulo_eleitor(), 
                c.getnacionalidade(), c.getnaturalidade(), c.getuf_n(), c.getcam(), 
                c.gettelefone(), c.getcelular(), c.getendereco(), c.getcidade(), 
                c.getbairro(), c.getcep(), c.getuf(), c.getemail(), c.getpis_pasep(),
                c.getctps(), c.getuf_c(), c.getcargo(), c.getdata_admissao(),
                c.getremuneracao(), c.gethorario_trabalho()
            });
        }
    }//GEN-LAST:event_pesquisarFuncActionPerformed

    private void avancar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avancar2ActionPerformed
        //Muda para a tela de cadastro II
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_avancar2ActionPerformed

    private void avancar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avancar3ActionPerformed
        //Muda para a tela de cadastro III
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_avancar3ActionPerformed

    private void tabelaFuncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaFuncMouseClicked
        /*int i = tabelaFunc.getSelectedRow();
        TableModel model = tabelaFunc.getModel();
        
        nomeCadFunc.setText(model.getValueAt(i, 1).toString());
        cpfCadFunc.setText(model.getValueAt(i, 2).toString());
        rgCadFunc.setText(model.getValueAt(i, 3).toString());
        nascCadFunc.setText(model.getValueAt(i, 4).toString());
        paiCadFunc.setText(model.getValueAt(i, 5).toString());
        maeCadFunc.setText(model.getValueAt(i, 6).toString());       
        String civil = model.getValueAt(i, 7).toString();
            if(civil.equals("Solteiro(a)")){
                civilCadFunc.setSelectedIndex(0);
            }
            else if(civil.equals("Casado(a)")){
                civilCadFunc.setSelectedIndex(1);
            }
            else if(civil.equals("Divorciado(a)")){
                civilCadFunc.setSelectedIndex(2);
            }
            else if(civil.equals("Separado(a)")){
                civilCadFunc.setSelectedIndex(3);
            }
            else if(civil.equals("Viúvo(a)")){
                civilCadFunc.setSelectedIndex(4);
            }
            else{
                civilCadFunc.setSelectedIndex(5);
            }
        eleitorCadFunc.setText(model.getValueAt(i, 8).toString());
        nacCadFunc.setText(model.getValueAt(i, 9).toString());
        natCadFunc.setText(model.getValueAt(i, 10).toString());
        nat_ufCadFunc.setText(model.getValueAt(i, 11).toString());
        camCadFunc.setText(model.getValueAt(i, 12).toString());
        telCadFunc.setText(model.getValueAt(i, 13).toString());
        celCadFunc.setText(model.getValueAt(i, 14).toString());
        endCadFunc.setText(model.getValueAt(i, 15).toString());
        cidadeCadFunc.setText(model.getValueAt(i, 16).toString());
        bairroCadFunc.setText(model.getValueAt(i, 17).toString());
        cepCadFunc.setText(model.getValueAt(i, 18).toString());
        cidade_ufCadFunc.setText(model.getValueAt(i, 19).toString());
        emailCadFunc.setText(model.getValueAt(i, 20).toString());
        pisCadFunc.setText(model.getValueAt(i, 21).toString());
        ctpsCadFunc.setText(model.getValueAt(i, 22).toString());
        uf_ctpsCadFunc.setText(model.getValueAt(i, 23).toString());
        cargoCadFunc.setText(model.getValueAt(i, 24).toString());
        admissaoCadFunc.setText(model.getValueAt(i, 25).toString());
        remunerCadFunc.setText(model.getValueAt(i, 26).toString());         
        jornadaCadFunc.setText(model.getValueAt(i, 27).toString());*/
    }//GEN-LAST:event_tabelaFuncMouseClicked

    private void cpfCadFuncFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cpfCadFuncFocusLost
       FuncionariosDao Funcionarios = new FuncionariosDao();
       Funcionarios f = Funcionarios.getFuncionariosPorCPF(cpfCadFunc.getText());
       // Fill Form 
       
        if (f != null) {
            nomeCadFunc.setText(f.getnome());
            nascCadFunc.setText(f.getdata_nacimento());
            paiCadFunc.setText(f.getnome_pai());
            telCadFunc.setText(f.gettelefone());
            maeCadFunc.setText(f.getnome_mae());
            celCadFunc.setText(f.getcelular());
            civilCadFunc.setSelectedItem(f.getestado_civil());
            rgCadFunc.setText(f.getrg());
            eleitorCadFunc.setText(f.gettitulo_eleitor());
            nacCadFunc.setText(f.getnacionalidade());
            natCadFunc.setText(f.getnaturalidade());
            nat_ufCadFunc.setText(f.getuf_n());
            camCadFunc.setText(f.getcam());
            cidadeCadFunc.setText(f.getcidade());
            cidade_ufCadFunc.setText(f.getuf());
            endCadFunc.setText(f.getendereco());
            cepCadFunc.setText(f.getcep());
            bairroCadFunc.setText(f.getbairro());
            emailCadFunc.setText(f.getemail());
            pisCadFunc.setText(f.getpis_pasep());
            ctpsCadFunc.setText(f.getctps());
            uf_ctpsCadFunc.setText(f.getuf_c());
            cargoCadFunc.setText(f.getcargo());
            admissaoCadFunc.setText(f.getdata_admissao());
            remunerCadFunc.setText(Float.toString(f.getremuneracao()));
            jornadaCadFunc.setText(Integer.toString(f.gethorario_trabalho()));
            
            
        } else {
            JOptionPane.showMessageDialog(null, "Funcionario não encontrado");
        }
        
    }//GEN-LAST:event_cpfCadFuncFocusLost

    private void voltarFuncionarios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarFuncionarios1ActionPerformed
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_voltarFuncionarios1ActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        limparFuncionario();
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void atualizarCadFunc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarCadFunc1ActionPerformed
        Funcionarios Funcionarios = new Funcionarios();
        FuncionariosDao cdao = new FuncionariosDao();
        
        // Fill Form
        Funcionarios.setnome(nomeCadFunc.getText());
        Funcionarios.setcpf(cpfCadFunc.getText());
        Funcionarios.setrg(rgCadFunc.getText());
        Funcionarios.setdata_nascimento(nascCadFunc.getText());
        Funcionarios.setnome_pai(paiCadFunc.getText());
        Funcionarios.setnome_mae(maeCadFunc.getText());
        Funcionarios.setestado_civil(String.valueOf(civilCadFunc.getSelectedItem()));   
        Funcionarios.settitulo_eleitor(eleitorCadFunc.getText());
        Funcionarios.setnacionalidade(nacCadFunc.getText());
        Funcionarios.setnaturalidade(natCadFunc.getText());
        Funcionarios.setuf_n(nat_ufCadFunc.getText());
        Funcionarios.setcam(camCadFunc.getText());  
        Funcionarios.settelefone(telCadFunc.getText());
        Funcionarios.setcelular(celCadFunc.getText());
        Funcionarios.setendereco(endCadFunc.getText() + "," + end_numCadFunc.getText());
        Funcionarios.setcidade(cidadeCadFunc.getText());
        Funcionarios.setbairro(bairroCadFunc.getText());
        Funcionarios.setcep(cepCadFunc.getText());
        Funcionarios.setuf(cidade_ufCadFunc.getText());
        Funcionarios.setemail(emailCadFunc.getText());
        Funcionarios.setpis_pasep(pisCadFunc.getText());
        Funcionarios.setctps(ctpsCadFunc.getText());
        Funcionarios.setuf_c(uf_ctpsCadFunc.getText());
        Funcionarios.setcargo(cargoCadFunc.getText());
        Funcionarios.setdata_admissao(admissaoCadFunc.getText());
        Funcionarios.setremuneracao(Float.parseFloat(remunerCadFunc.getText()));         
        Funcionarios.sethorario_trabalho(Integer.parseInt(jornadaCadFunc.getText()));   
        Funcionarios.setcpf(cpfCadFunc.getText());
        cdao.update(Funcionarios);
        
        // Clear Form
        limparFuncionario();
    }//GEN-LAST:event_atualizarCadFunc1ActionPerformed

    private void excluirCadFunc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirCadFunc1ActionPerformed
        Funcionarios Funcionarios = new Funcionarios();
        FuncionariosDao cdao = new FuncionariosDao();
        // Fill Form

        Funcionarios.setcpf(cpfCadFunc.getText()); 
        cdao.delete(Funcionarios);
        
        // Clear Form
        limparFuncionario();
    }//GEN-LAST:event_excluirCadFunc1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela04_B6_TabbedFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela04_B6_TabbedFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela04_B6_TabbedFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela04_B6_TabbedFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela04_B6_TabbedFuncionarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField admissaoCadFunc;
    private javax.swing.JButton atualizarCadFunc;
    private javax.swing.JButton atualizarCadFunc1;
    private javax.swing.JButton atualizarCadFunc2;
    private javax.swing.JButton avancar2;
    private javax.swing.JButton avancar3;
    private javax.swing.JTextField bairroCadFunc;
    private javax.swing.JFormattedTextField camCadFunc;
    private javax.swing.JTextField cargoCadFunc;
    private javax.swing.JFormattedTextField celCadFunc;
    private javax.swing.JFormattedTextField cepCadFunc;
    private javax.swing.JTextField cidadeCadFunc;
    private javax.swing.JTextField cidade_ufCadFunc;
    private javax.swing.JComboBox<String> civilCadFunc;
    private javax.swing.JTextField compCadFunc;
    private javax.swing.JFormattedTextField cpfCadFunc;
    private javax.swing.JFormattedTextField ctpsCadFunc;
    private javax.swing.JFormattedTextField eleitorCadFunc;
    private javax.swing.JTextField emailCadFunc;
    private javax.swing.JTextField endCadFunc;
    private javax.swing.JTextField end_numCadFunc;
    private javax.swing.JButton excluirCadFunc;
    private javax.swing.JButton excluirCadFunc1;
    private javax.swing.JButton excluirCadFunc2;
    private javax.swing.JButton inserirCadFunc2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jornadaCadFunc;
    private javax.swing.JTextField maeCadFunc;
    private javax.swing.JTextField nacCadFunc;
    private javax.swing.JFormattedTextField nascCadFunc;
    private javax.swing.JTextField natCadFunc;
    private javax.swing.JTextField nat_ufCadFunc;
    private javax.swing.JTextField nomeCadFunc;
    private javax.swing.JTextField paiCadFunc;
    private javax.swing.JTextField pesquisaFunc;
    private javax.swing.JButton pesquisarFunc;
    private javax.swing.JFormattedTextField pisCadFunc;
    private javax.swing.JTextField remunerCadFunc;
    private javax.swing.JFormattedTextField rgCadFunc;
    private javax.swing.JTable tabelaFunc;
    private javax.swing.JFormattedTextField telCadFunc;
    private javax.swing.JTextField uf_ctpsCadFunc;
    private javax.swing.JButton voltarCadFunc;
    private javax.swing.JButton voltarCadFunc1;
    private javax.swing.JButton voltarCadFunc2;
    private javax.swing.JButton voltarFuncionarios;
    private javax.swing.JButton voltarFuncionarios1;
    // End of variables declaration//GEN-END:variables
}
