/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import java.text.DateFormat;                                                    //NÃO TEM NO NOVO TABBED
import java.text.SimpleDateFormat;                                              //NÃO TEM NO NOVO TABBED
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;                                     //NÃO TEM NO NOVO TABBED    
import model.AgendamentoSumario;                                                //NÃO TEM NO NOVO TABBED
import model.Agendamento_servicos;                                              //NÃO TEM NO NOVO TABBED            
import model.Agendamento_servicosDao;                                           //NÃO TEM NO NOVO TABBED
import model.Agendamentos;                                                      //NÃO TEM NO NOVO TABBED
import model.AgendamentosDao;                                                   //NÃO TEM NO NOVO TABBED
import model.Clientes;                                                          //NÃO TEM NO NOVO TABBED
import model.ClientesDao;                                                       //NÃO TEM NO NOVO TABBED
import model.Pets;                                                              //NÃO TEM NO NOVO TABBED
import model.PetsDao;                                                           //NÃO TEM NO NOVO TABBED
import model.Servico_precosDao;
import model.Servicos_precos;
import model.ComboItem;                                                         //ADD PELO NOVO TABBED
import model.Funcionarios;                                                      //ADD PELO NOVO TABBED
import model.FuncionariosDao;                                                   //ADD PELO NOVO TABBED
import model.Servicos;                                                          //ADD PELO NOVO TABBED
import model.ServicosDao;                                                       //ADD PELO NOVO TABBED
import javax.swing.ComboBoxModel;                                               //ADD PELO NOVO TABBED
import javax.swing.JComboBox;                                                   //ADD PELO NOVO TABBED
import javax.swing.table.TableModel;
/**
 *
 * @author Denise Trevizo (usp)
 */
public class Tela04_B4_TabbedServicosGerencia extends javax.swing.JFrame {

    /**
     * Creates new form TabbedClientesGerencia
     */
    public Tela04_B4_TabbedServicosGerencia() {
        initComponents();
        
        codCliAgendServ.setVisible(false);                                      //NÃO TEM NO NOVO TABBED
        codPetAgendServ.setVisible(false);                                      //NÃO TEM NO NOVO TABBED
        porteAgendServ.setEditable(false);                                      //NÃO TEM NO NOVO TABBED
        
        // Oculta IDS                                                           //ADD PELO NOVO TABBED
        codServ.setVisible(false);                                            

        // Popular Funcionarios                                                 //ADD PELO NOVO TABBED
        FuncionariosDao dao = new FuncionariosDao();
        ArrayList<Funcionarios> funcs = dao.all();

        for (Funcionarios func : funcs) {                                       //ADD PELO NOVO TABBED
            funcCadServ.addItem(new ComboItem(func.getcod_func(), func.getnome()));
        }    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        voltarAgendamentos = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaAgend = new javax.swing.JTable();
        pesquisaAgend = new javax.swing.JTextField();
        btnPesquisarAgend = new javax.swing.JButton();
        avancarServicos = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        banhoAgendServ = new javax.swing.JCheckBox();
        tosaAgendServ = new javax.swing.JCheckBox();
        tosa_higAgendServ = new javax.swing.JCheckBox();
        escovacaoAgendServ = new javax.swing.JCheckBox();
        unhasAgendServ = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        codPetAgendServ = new javax.swing.JTextField();
        porteAgendServ = new javax.swing.JTextField();
        codCliAgendServ = new javax.swing.JTextField();
        voltarAgendServ = new javax.swing.JButton();
        inserirAgendServ = new javax.swing.JButton();
        dataAgendServ = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        totalAgendServ = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        horarioAgendServ = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        petAgendServ = new javax.swing.JTextField();
        cpfAgendServ = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        clienteAgendServ = new javax.swing.JTextField();
        statusAgendServ = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        servicoCadServ = new javax.swing.JTextField();
        atualizarCadServ = new javax.swing.JButton();
        voltarCadServ = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        minPCadServ = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        minMCadServ = new javax.swing.JTextField();
        minGCadServ = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        valorPCadServ = new javax.swing.JTextField();
        valorMCadServ = new javax.swing.JTextField();
        valorGCadServ = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        obsCadServ = new javax.swing.JTextField();
        codServ = new javax.swing.JTextField();
        funcCadServ = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(242, 242, 242));
        jTabbedPane1.setForeground(new java.awt.Color(67, 1, 101));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTabbedPane1.setOpaque(true);
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(603, 423));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 208, 119));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(67, 1, 101));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Consultar Agendamentos");
        jLabel2.setOpaque(true);

        voltarAgendamentos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        voltarAgendamentos.setForeground(new java.awt.Color(204, 0, 0));
        voltarAgendamentos.setText("<<");
        voltarAgendamentos.setBorderPainted(false);
        voltarAgendamentos.setContentAreaFilled(false);
        voltarAgendamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarAgendamentosActionPerformed(evt);
            }
        });

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tabelaAgend.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tabelaAgend.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Data", "Horário", "Cliente", "CPF", "Pet", "Porte", "Serviço", "Status"
            }
        ));
        tabelaAgend.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabelaAgend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaAgendMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaAgend);

        pesquisaAgend.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        btnPesquisarAgend.setBackground(new java.awt.Color(30, 0, 45));
        btnPesquisarAgend.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnPesquisarAgend.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisarAgend.setText("Pesquisar");
        btnPesquisarAgend.setBorderPainted(false);
        btnPesquisarAgend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarAgendActionPerformed(evt);
            }
        });

        avancarServicos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        avancarServicos.setForeground(new java.awt.Color(36, 99, 36));
        avancarServicos.setText(">>");
        avancarServicos.setBorderPainted(false);
        avancarServicos.setContentAreaFilled(false);
        avancarServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avancarServicosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(voltarAgendamentos)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(pesquisaAgend)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisarAgend))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(avancarServicos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesquisaAgend, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarAgend, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 25, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(avancarServicos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(voltarAgendamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Consulta", jPanel3);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        banhoAgendServ.setBackground(new java.awt.Color(255, 255, 255));
        banhoAgendServ.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        banhoAgendServ.setText("Banho");
        banhoAgendServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                banhoAgendServActionPerformed(evt);
            }
        });

        tosaAgendServ.setBackground(new java.awt.Color(255, 255, 255));
        tosaAgendServ.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tosaAgendServ.setText("Tosa");
        tosaAgendServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tosaAgendServActionPerformed(evt);
            }
        });

        tosa_higAgendServ.setBackground(new java.awt.Color(255, 255, 255));
        tosa_higAgendServ.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tosa_higAgendServ.setText("Tosa higiênica");
        tosa_higAgendServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tosa_higAgendServActionPerformed(evt);
            }
        });

        escovacaoAgendServ.setBackground(new java.awt.Color(255, 255, 255));
        escovacaoAgendServ.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        escovacaoAgendServ.setText("Escovação de dentes");
        escovacaoAgendServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escovacaoAgendServActionPerformed(evt);
            }
        });

        unhasAgendServ.setBackground(new java.awt.Color(255, 255, 255));
        unhasAgendServ.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        unhasAgendServ.setText("Corte de unhas");
        unhasAgendServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unhasAgendServActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(banhoAgendServ)
                    .addComponent(tosaAgendServ)
                    .addComponent(tosa_higAgendServ)
                    .addComponent(unhasAgendServ))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(escovacaoAgendServ)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(banhoAgendServ, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tosaAgendServ, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tosa_higAgendServ, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(escovacaoAgendServ, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unhasAgendServ, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Serviços");

        codPetAgendServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codPetAgendServActionPerformed(evt);
            }
        });

        codCliAgendServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codCliAgendServActionPerformed(evt);
            }
        });

        voltarAgendServ.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        voltarAgendServ.setForeground(new java.awt.Color(204, 0, 0));
        voltarAgendServ.setText("<<");
        voltarAgendServ.setBorderPainted(false);
        voltarAgendServ.setContentAreaFilled(false);
        voltarAgendServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarAgendServActionPerformed(evt);
            }
        });

        inserirAgendServ.setBackground(new java.awt.Color(30, 0, 45));
        inserirAgendServ.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        inserirAgendServ.setForeground(new java.awt.Color(255, 255, 255));
        inserirAgendServ.setText("Inserir");
        inserirAgendServ.setBorderPainted(false);
        inserirAgendServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirAgendServActionPerformed(evt);
            }
        });

        dataAgendServ.setDateFormatString("dd-MM-yyyy");
        dataAgendServ.setMinSelectableDate(new java.util.Date(-62135755129000L));

        jLabel1.setBackground(new java.awt.Color(255, 208, 119));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(67, 1, 101));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Realizar Agendamentos");
        jLabel1.setOpaque(true);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Porte");

        totalAgendServ.setBackground(new java.awt.Color(222, 213, 226));
        totalAgendServ.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        totalAgendServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalAgendServActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Total");

        try {
            horarioAgendServ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        horarioAgendServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horarioAgendServActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Horário");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("CPF");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Pet");

        petAgendServ.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        petAgendServ.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                petAgendServbuscarPet(evt);
            }
        });

        try {
            cpfAgendServ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpfAgendServ.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cpfAgendServbuscarCliente(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Data");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Cliente");

        clienteAgendServ.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Status");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inserirAgendServ))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statusAgendServ, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(dataAgendServ, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(horarioAgendServ)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(totalAgendServ, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(cpfAgendServ, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clienteAgendServ)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(petAgendServ)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(porteAgendServ)
                            .addComponent(jLabel14))))
                .addGap(85, 85, 85))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(voltarAgendServ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(codCliAgendServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(codPetAgendServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel8)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(horarioAgendServ, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dataAgendServ, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(statusAgendServ, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clienteAgendServ, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cpfAgendServ, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(petAgendServ, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(porteAgendServ, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(voltarAgendServ))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalAgendServ, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(inserirAgendServ, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(codCliAgendServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codPetAgendServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agendamento", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setBackground(new java.awt.Color(255, 208, 119));
        jLabel6.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(67, 1, 101));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Atualizar Serviços");
        jLabel6.setOpaque(true);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Serviço");

        servicoCadServ.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                servicoCadServFocusLost(evt);
            }
        });

        atualizarCadServ.setBackground(new java.awt.Color(30, 0, 45));
        atualizarCadServ.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        atualizarCadServ.setForeground(new java.awt.Color(255, 255, 255));
        atualizarCadServ.setText("Atualizar");
        atualizarCadServ.setBorderPainted(false);
        atualizarCadServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarCadServActionPerformed(evt);
            }
        });

        voltarCadServ.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        voltarCadServ.setForeground(new java.awt.Color(204, 0, 0));
        voltarCadServ.setText("<<");
        voltarCadServ.setBorderPainted(false);
        voltarCadServ.setContentAreaFilled(false);
        voltarCadServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarCadServActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setText("Minutos");

        minPCadServ.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        minPCadServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minPCadServActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 51, 51));
        jLabel25.setText("Valor");

        jLabel24.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setText("Pequeno");

        minMCadServ.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        minMCadServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minMCadServActionPerformed(evt);
            }
        });

        minGCadServ.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        minGCadServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minGCadServActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 51, 51));
        jLabel26.setText("Médio");

        jLabel27.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 51, 51));
        jLabel27.setText("Grande");

        valorPCadServ.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        valorPCadServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorPCadServActionPerformed(evt);
            }
        });

        valorMCadServ.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        valorMCadServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorMCadServActionPerformed(evt);
            }
        });

        valorGCadServ.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        valorGCadServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorGCadServActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 51, 51));
        jLabel28.setText("Porte");

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Funcionário ");

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("Observação");

        codServ.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        codServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codServActionPerformed(evt);
            }
        });

        //funcCadServ = new javax.swing.JComboBox<>();  ANTES
        funcCadServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcCadServActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(voltarCadServ)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel18)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel16)
                                    .addComponent(servicoCadServ, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                    .addComponent(jLabel17)
                                    .addComponent(funcCadServ, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel24)
                                            .addComponent(jLabel28))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel23)
                                            .addComponent(minPCadServ, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel26)
                                            .addComponent(jLabel27))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(minMCadServ, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                            .addComponent(minGCadServ))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel25)
                                    .addComponent(valorGCadServ, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                    .addComponent(valorMCadServ)
                                    .addComponent(valorPCadServ)))
                            .addComponent(obsCadServ)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(codServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(atualizarCadServ)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(servicoCadServ, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(funcCadServ, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jLabel25)
                            .addComponent(jLabel28))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(minPCadServ, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24)
                            .addComponent(valorPCadServ, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(minMCadServ, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26)
                            .addComponent(valorMCadServ, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(minGCadServ, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27)
                            .addComponent(valorGCadServ, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(obsCadServ, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(voltarCadServ, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(atualizarCadServ, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codServ, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))))
        );

        jTabbedPane1.addTab("Atualização Serviço", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void funcCadServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcCadServActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_funcCadServActionPerformed

    private void codServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codServActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codServActionPerformed

    private void valorGCadServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorGCadServActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorGCadServActionPerformed

    private void valorMCadServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorMCadServActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorMCadServActionPerformed

    private void valorPCadServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorPCadServActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorPCadServActionPerformed

    private void minGCadServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minGCadServActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minGCadServActionPerformed

    private void minMCadServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minMCadServActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minMCadServActionPerformed

    private void minPCadServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minPCadServActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minPCadServActionPerformed

    private void voltarCadServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarCadServActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_voltarCadServActionPerformed

    private void atualizarCadServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarCadServActionPerformed
        ServicosDao servDao = new ServicosDao();                                //ADD PELO NOVO TABBED
        Servico_precosDao servPrecosDao = new Servico_precosDao();

        Servicos serv = new Servicos();
        serv.setcod_serv(Integer.parseInt(codServ.getText()));
        serv.setnome(servicoCadServ.getText());
        serv.setdescricao(obsCadServ.getText());
        serv.setcod_fun(getSelectedValue(funcCadServ));

        Servicos_precos p = null;
        Servicos_precos m = null;
        Servicos_precos g = null;

        if (!minPCadServ.getText().equals("")) {
            p = servPrecosDao.getPorPorte(serv.getcod_serv(), "P");             //PRECISA MUDAR?

            if (p != null) {
                p.setcod_serv(serv.getcod_serv());
                p.setporte("P");
                p.settempo(minPCadServ.getText());
                p.setvalor(Double.parseDouble(valorPCadServ.getText()));
                servPrecosDao.updateAtualizacao(p);                             //NOME ALTERADO "UPDATE" > "UPDATEATUALIZACAO", SERVICOPRECOSDAO
            } else {
                p = new Servicos_precos();
                p.setcod_serv(serv.getcod_serv());
                p.setporte("P");
                p.settempo(minPCadServ.getText());
                p.setvalor(Double.parseDouble(valorPCadServ.getText()));
                servPrecosDao.createAtualizacao(p);                             //NOME ALTERADO "CREATE" > "CREATEATUALIZACAO", SERVICOPRECOSDAO
            }

        }
        if (!minMCadServ.getText().equals("")) {
            m = servPrecosDao.getPorPorte(serv.getcod_serv(), "M");

            if (m != null) {
                m.setcod_serv(serv.getcod_serv());
                m.setporte("M");
                m.settempo(minMCadServ.getText());
                m.setvalor(Double.parseDouble(valorMCadServ.getText()));
                servPrecosDao.updateAtualizacao(m);                             //NOME ALTERADO "UPDATE" > "UPDATEATUALIZACAO", SERVICOPRECOSDAO
            } else {
                m = new Servicos_precos();
                m.setcod_serv(serv.getcod_serv());
                m.setporte("M");
                m.settempo(minMCadServ.getText());
                m.setvalor(Double.parseDouble(valorMCadServ.getText()));
                servPrecosDao.createAtualizacao(m);                             //NOME ALTERADO "CREATE" > "CREATEATUALIZACAO", SERVICOPRECOSDAO
            }

        }
        if (!minGCadServ.getText().equals("")) {
            g = servPrecosDao.getPorPorte(serv.getcod_serv(), "G");

            if (g != null) {
                g.setcod_serv(serv.getcod_serv());
                g.setporte("G");
                g.settempo(minGCadServ.getText());
                g.setvalor(Double.parseDouble(valorGCadServ.getText()));
                servPrecosDao.updateAtualizacao(g);                             //NOME ALTERADO "UPDATE" > "UPDATEATUALIZACAO", SERVICOPRECOSDAO
            } else {
                g = new Servicos_precos();
                g.setcod_serv(serv.getcod_serv());
                g.setporte("G");
                g.settempo(minGCadServ.getText());
                g.setvalor(Double.parseDouble(valorGCadServ.getText()));
                servPrecosDao.createAtualizacao(g);                             //NOME ALTERADO "CREATE" > "CREATEATUALIZACAO", SERVICOPRECOSDAO
            }
        }

        servDao.updateAtualizacao(serv);                                        //ALTERADO "UPDATE" > "UPDATEATUALIZACAO", SERVICOSDAO
        JOptionPane.showMessageDialog(null, "Serviço salvo com sucesso.");
    }//GEN-LAST:event_atualizarCadServActionPerformed

    private void servicoCadServFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_servicoCadServFocusLost
        ServicosDao servDao = new ServicosDao();                                //ADD PELO NOVO TABBED
        Servico_precosDao servPrecosDao = new Servico_precosDao();

        Servicos serv = servDao.getPorNome(servicoCadServ.getText());
        if (serv == null) {
            JOptionPane.showMessageDialog(null, "Serviço não encontrado.");
            limparCampos();
            return;
        }

        // Preenche serviço
        limparCampos();
        servicoCadServ.setText(serv.getnome());
        obsCadServ.setText(serv.getdescricao());
        codServ.setText(Integer.toString(serv.getcod_serv()));

        if (serv.getcod_fun() > 0) {
            setSelectedValue(funcCadServ, serv.getcod_fun());
        }

        // Preenche preços
        ArrayList<Servicos_precos> precos = servPrecosDao.getPorServico(serv.getcod_serv());
        if (precos.size() > 0) {
            for (Servicos_precos preco : precos) {
                if (preco.getporte().equals("P")) {
                    minPCadServ.setText(preco.gettempo());
                    valorPCadServ.setText(Double.toString(preco.getvalor()));
                }

                if (preco.getporte().equals("M")) {
                    minMCadServ.setText(preco.gettempo());
                    valorMCadServ.setText(Double.toString(preco.getvalor()));
                }

                if (preco.getporte().equals("G")) {
                    minGCadServ.setText(preco.gettempo());
                    valorGCadServ.setText(Double.toString(preco.getvalor()));
                }
            }
        }
    }//GEN-LAST:event_servicoCadServFocusLost

    private void cpfAgendServbuscarCliente(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cpfAgendServbuscarCliente
        ClientesDao dao = new ClientesDao();
        Clientes cliente = dao.getClientePorCPF(cpfAgendServ.getText());

        if (cliente != null) {
            cpfAgendServ.setText(cliente.getcpf());
            clienteAgendServ.setText(cliente.getnome());
            codCliAgendServ.setText(cliente.getcod_cli().toString());
        } else {
            cpfAgendServ.setText("");
            clienteAgendServ.setText("");
            codCliAgendServ.setText("");
            JOptionPane.showMessageDialog(null, "Cliente não encontrado");
        }
    }//GEN-LAST:event_cpfAgendServbuscarCliente

    private void petAgendServbuscarPet(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_petAgendServbuscarPet
        // TODO add your handling code here:
        PetsDao dao = new PetsDao();
        Pets pets = dao.getPorNomeEDono(petAgendServ.getText(), Integer.parseInt(codCliAgendServ.getText()));

        if (pets != null) {
            petAgendServ.setText(pets.getnome());
            porteAgendServ.setText(pets.getporte());
            codPetAgendServ.setText(pets.getcod_pet().toString());
        } else {
            petAgendServ.setText("");
            porteAgendServ.setText("");
            codPetAgendServ.setText("");
            JOptionPane.showMessageDialog(null, "Pet não encontrado");
        }
    }//GEN-LAST:event_petAgendServbuscarPet

    private void horarioAgendServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horarioAgendServActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horarioAgendServActionPerformed

    private void totalAgendServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalAgendServActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalAgendServActionPerformed

    private void inserirAgendServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirAgendServActionPerformed
        cadastrarAgendamento();                                                 //NÃO TEM NO NOVO TABBED
    }//GEN-LAST:event_inserirAgendServActionPerformed

    private void voltarAgendServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarAgendServActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_voltarAgendServActionPerformed

    private void codCliAgendServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codCliAgendServActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codCliAgendServActionPerformed

    private void codPetAgendServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codPetAgendServActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codPetAgendServActionPerformed

    private void unhasAgendServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unhasAgendServActionPerformed
        // TODO add your handling code here:
        calcularServicoTotal();
    }//GEN-LAST:event_unhasAgendServActionPerformed

    private void escovacaoAgendServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escovacaoAgendServActionPerformed
        // TODO add your handling code here:
        calcularServicoTotal();
    }//GEN-LAST:event_escovacaoAgendServActionPerformed

    private void tosa_higAgendServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tosa_higAgendServActionPerformed
        // TODO add your handling code here:
        calcularServicoTotal();
    }//GEN-LAST:event_tosa_higAgendServActionPerformed

    private void tosaAgendServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tosaAgendServActionPerformed
        // TODO add your handling code here:
        calcularServicoTotal();
    }//GEN-LAST:event_tosaAgendServActionPerformed

    private void banhoAgendServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_banhoAgendServActionPerformed
        // TODO add your handling code here:
        calcularServicoTotal();
    }//GEN-LAST:event_banhoAgendServActionPerformed

    private void avancarServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avancarServicosActionPerformed
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_avancarServicosActionPerformed

    private void btnPesquisarAgendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarAgendActionPerformed
        AgendamentosDao dao = new AgendamentosDao();                            //NÃO TEM NO NOVO TABBED
        ArrayList<AgendamentoSumario> agendamentos = dao.getAgendamento();

        DefaultTableModel tabelaProdutos = (DefaultTableModel) tabelaAgend.getModel();
        tabelaProdutos.setNumRows(0);
        for (AgendamentoSumario a : agendamentos) {
            tabelaProdutos.addRow(new Object[]{
                a.getcod_age(),
                a.getdata(),
                a.gethora(),
                a.getcliente(),
                a.getcpf(),
                a.getpet(),
                a.getporte(),
                a.getservico(),
                a.getstatus_agend()
            });
        }
    }//GEN-LAST:event_btnPesquisarAgendActionPerformed

    private void tabelaAgendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaAgendMouseClicked

    }//GEN-LAST:event_tabelaAgendMouseClicked

    private void voltarAgendamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarAgendamentosActionPerformed
        Tela03_B_HomeGerencia telaHomeGerencia = new Tela03_B_HomeGerencia();
        telaHomeGerencia.setVisible(true);
        dispose();
    }//GEN-LAST:event_voltarAgendamentosActionPerformed
    
    private void limparCampos() {                                               //ADD PELO NOVO TABBED    
        servicoCadServ.setText("");
        obsCadServ.setText("");
        codServ.setText("");

        minPCadServ.setText("");
        valorPCadServ.setText("");
        minMCadServ.setText("");
        valorMCadServ.setText("");
        minGCadServ.setText("");
        valorGCadServ.setText("");
    }
    
    private static void setSelectedValue(JComboBox comboBox, int value) {       //ADD PELO NOVO TABBED
        ComboItem item;
        for (int i = 0; i < comboBox.getItemCount(); i++) {
            item = (ComboItem) comboBox.getItemAt(i);
            if (item.Chave == value) {
                comboBox.setSelectedIndex(i);
                break;
            }
        }
    }

    private static int getSelectedValue(JComboBox comboBox) {                   //ADD PELO NOVO TABBED
        ComboItem item = (ComboItem) comboBox.getSelectedItem();
        return item.Chave;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela04_B4_TabbedServicosGerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela04_B4_TabbedServicosGerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela04_B4_TabbedServicosGerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela04_B4_TabbedServicosGerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela04_B4_TabbedServicosGerencia().setVisible(true);
            }
        });
    }
    
    private void cadastrarAgendamento() {
        String pattern = "yyyy-MM-dd";
        DateFormat df = new SimpleDateFormat(pattern);
        
        AgendamentosDao agendamentos = new AgendamentosDao();
        Agendamento_servicosDao agendaServs = new Agendamento_servicosDao();

        Agendamentos agendamento = new Agendamentos();
        agendamento.setcod_pet(Integer.parseInt(codPetAgendServ.getText()));
        agendamento.setdata_agendada(df.format(dataAgendServ.getDate()));
        agendamento.sethora_agendada(horarioAgendServ.getText());   //ADD
        agendamento.setstatus_agend(statusAgendServ.getText());   //ADD

        agendamentos.create(agendamento);

        Agendamento_servicos serv = new Agendamento_servicos();
        serv.setcod_age(agendamento.getcod_age());
        if (banhoAgendServ.isSelected()) {
            serv.setcod_serv(1);
            agendaServs.create(serv);
        }

        if (tosaAgendServ.isSelected()) {
            serv.setcod_serv(2);
            agendaServs.create(serv);
        }

        if (tosa_higAgendServ.isSelected()) {
            serv.setcod_serv(3);
            agendaServs.create(serv);
        }

        if (escovacaoAgendServ.isSelected()) {
            serv.setcod_serv(4);
            agendaServs.create(serv);
        }

        if (unhasAgendServ.isSelected()) {
            serv.setcod_serv(5);
            agendaServs.create(serv);
        }

        JOptionPane.showMessageDialog(null, "Agendamento cadastrado com sucesso.");
    }

    private void calcularServicoTotal() {
        double total = 0.0;
        Servico_precosDao dao = new Servico_precosDao();

        if (banhoAgendServ.isSelected()) {
            Servicos_precos banho = dao.getPorPorte(1, porteAgendServ.getText());
            if (banho != null) {
                total += banho.getvalor();
            }
        }

        if (tosaAgendServ.isSelected()) {
            Servicos_precos banho = dao.getPorPorte(2, porteAgendServ.getText());
            if (banho != null) {
                total += banho.getvalor();
            }
        }

        if (tosa_higAgendServ.isSelected()) {
            Servicos_precos banho = dao.getPorPorte(3, porteAgendServ.getText());
            if (banho != null) {
                total += banho.getvalor();
            }
        }

        if (escovacaoAgendServ.isSelected()) {
            Servicos_precos banho = dao.getPorPorte(4, porteAgendServ.getText());
            if (banho != null) {
                total += banho.getvalor();
            }
        }

        if (unhasAgendServ.isSelected()) {
            Servicos_precos banho = dao.getPorPorte(5, porteAgendServ.getText());
            if (banho != null) {
                total += banho.getvalor();
            }
        }

        totalAgendServ.setText(String.valueOf(total));
    }    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarCadServ;
    private javax.swing.JButton avancarServicos;
    private javax.swing.JCheckBox banhoAgendServ;
    private javax.swing.JButton btnPesquisarAgend;
    private javax.swing.JTextField clienteAgendServ;
    private javax.swing.JTextField codCliAgendServ;
    private javax.swing.JTextField codPetAgendServ;
    private javax.swing.JTextField codServ;
    private javax.swing.JFormattedTextField cpfAgendServ;
    private com.toedter.calendar.JDateChooser dataAgendServ;
    private javax.swing.JCheckBox escovacaoAgendServ;
    private javax.swing.JButton excluirCaixa;
    private javax.swing.JComboBox funcCadServ;
    private javax.swing.JFormattedTextField horarioAgendServ;
    private javax.swing.JButton inserirAgendServ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField minGCadServ;
    private javax.swing.JTextField minMCadServ;
    private javax.swing.JTextField minPCadServ;
    private javax.swing.JTextField obsCadServ;
    private javax.swing.JTextField pesquisaAgend;
    private javax.swing.JTextField petAgendServ;
    private javax.swing.JTextField porteAgendServ;
    private javax.swing.JTextField servicoCadServ;
    private javax.swing.JTextField statusAgendServ;
    private javax.swing.JTable tabelaAgend;
    private javax.swing.JCheckBox tosaAgendServ;
    private javax.swing.JCheckBox tosa_higAgendServ;
    private javax.swing.JTextField totalAgendServ;
    private javax.swing.JCheckBox unhasAgendServ;
    private javax.swing.JTextField valorGCadServ;
    private javax.swing.JTextField valorMCadServ;
    private javax.swing.JTextField valorPCadServ;
    private javax.swing.JButton voltarAgendServ;
    private javax.swing.JButton voltarAgendamentos;
    private javax.swing.JButton voltarCadServ;
    // End of variables declaration//GEN-END:variables
}
